import type { Locale } from "../types";

export interface InvoicePdfMessages {
  title: string;
  invoiceNumber: string;
  issueDate: string;
  dueDate: string;
  paymentDate: string;
  status: string;
  from: string;
  billTo: string;
  description: string;
  hours: string;
  amount: string;
  subtotal: string;
  total: string;
  notes: string;
  nbsRate: string;
  nbsRateEffective: string;
  rsdEquivalent: string;
  rateSource: string;
  bankAccount: string;
  taxId: string;
  registrationNumber: string;
  email: string;
  phone: string;
  disclaimer: string;
  generatedAt: string;
  statusDraft: string;
  statusIssued: string;
  statusPaid: string;
  statusOverdue: string;
  statusCancelled: string;
  serviceDescription: string;
  hourlyDescription: string;
}

const en: InvoicePdfMessages = {
  title: "INVOICE",
  invoiceNumber: "Invoice no.",
  issueDate: "Issue date",
  dueDate: "Due date",
  paymentDate: "Payment date",
  status: "Status",
  from: "From",
  billTo: "Bill to",
  description: "Description",
  hours: "Hours",
  amount: "Amount",
  subtotal: "Subtotal",
  total: "Total",
  notes: "Notes",
  nbsRate: "NBS middle rate",
  nbsRateEffective: "Rate effective date",
  rsdEquivalent: "RSD equivalent (planning)",
  rateSource: "Rate source",
  bankAccount: "Bank account",
  taxId: "Tax ID (PIB)",
  registrationNumber: "Company ID (MB)",
  email: "Email",
  phone: "Phone",
  disclaimer:
    "Generated by Invoice Limit Tracker Serbia for planning purposes only. Not a legally binding tax document. Verify exchange rates and invoice details with your accountant.",
  generatedAt: "Generated",
  statusDraft: "Draft",
  statusIssued: "Issued",
  statusPaid: "Paid",
  statusOverdue: "Overdue",
  statusCancelled: "Cancelled",
  serviceDescription: "Professional services",
  hourlyDescription: "Professional services (hourly)",
};

const sr: InvoicePdfMessages = {
  title: "FAKTURA",
  invoiceNumber: "Broj fakture",
  issueDate: "Datum izdavanja",
  dueDate: "Datum dospeća",
  paymentDate: "Datum plaćanja",
  status: "Status",
  from: "Od",
  billTo: "Za",
  description: "Opis",
  hours: "Sati",
  amount: "Iznos",
  subtotal: "Međuzbir",
  total: "Ukupno",
  notes: "Napomene",
  nbsRate: "NBS srednji kurs",
  nbsRateEffective: "Datum važenja kursa",
  rsdEquivalent: "RSD ekvivalent (planiranje)",
  rateSource: "Izvor kursa",
  bankAccount: "Tekući račun",
  taxId: "PIB",
  registrationNumber: "Matični broj",
  email: "Email",
  phone: "Telefon",
  disclaimer:
    "Generisano pomoću Praćenja limita faktura Srbija isključivo za potrebe planiranja. Nije pravno obavezujući poreski dokument. Proverite kurs i podatke fakture sa računovođom.",
  generatedAt: "Generisano",
  statusDraft: "Nacrt",
  statusIssued: "Izdato",
  statusPaid: "Plaćeno",
  statusOverdue: "Dospeo rok",
  statusCancelled: "Stornirano",
  serviceDescription: "Usluge",
  hourlyDescription: "Usluge (po satu)",
};

export function getInvoicePdfMessages(locale: Locale): InvoicePdfMessages {
  return locale === "sr" ? sr : en;
}
