import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { getOrgContextSafe } from "@/lib/auth/get-org-context";
import { formatDate, formatRate } from "@/lib/utils/format";

// CSV export — XLSX can be added with the xlsx package
export async function GET(req: NextRequest) {
  const ctx = await getOrgContextSafe();
  if (!ctx) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const params = req.nextUrl.searchParams;
  const year = params.get("year") ? parseInt(params.get("year")!) : new Date().getFullYear();
  const status = params.get("status") || undefined;
  const clientId = params.get("clientId") || undefined;
  const basis = (params.get("basis") ?? "ISSUE_DATE") as "ISSUE_DATE" | "PAYMENT_DATE";

  const dateField = basis === "ISSUE_DATE" ? "issueDate" : "paymentDate";

  const invoices = await prisma.invoice.findMany({
    where: {
      organizationId: ctx.organizationId,
      ...(status && { status: status as "DRAFT" | "ISSUED" | "PAID" | "OVERDUE" | "CANCELLED" }),
      ...(clientId && { clientId }),
      [dateField]: {
        gte: new Date(year, 0, 1),
        lte: new Date(year, 11, 31),
      },
    },
    include: { client: { select: { displayName: true, taxId: true } } },
    orderBy: { [dateField]: "asc" },
  });

  const headers = [
    "Invoice Number",
    "Client",
    "Client Tax ID",
    "Issue Date",
    "Payment Date",
    "Due Date",
    "Status",
    "Original Amount",
    "Currency",
    "NBS Rate (per unit)",
    "Rate Source",
    "Fallback Rate",
    "Manual Override",
    "RSD Amount",
    "Included in Limit",
    "Notes",
  ];

  const rows = invoices.map((inv: typeof invoices[0]) => [
    inv.invoiceNumber,
    inv.client?.displayName ?? "",
    inv.client?.taxId ?? "",
    formatDate(inv.issueDate),
    inv.paymentDate ? formatDate(inv.paymentDate) : "",
    inv.dueDate ? formatDate(inv.dueDate) : "",
    inv.status,
    inv.originalAmount.toString(),
    inv.currency,
    formatRate(inv.appliedMiddleRate.toString(), 6),
    inv.rateSource,
    inv.isFallbackRate ? "Yes" : "No",
    inv.manualOverride ? "Yes" : "No",
    inv.rsdAmount.toString(),
    inv.includeInLimit ? "Yes" : "No",
    inv.notes ?? "",
  ]);

  const csvRows = [headers, ...rows].map((row) =>
    row
      .map((cell: unknown) => {
        const str = String(cell ?? "");
        if (str.includes(",") || str.includes('"') || str.includes("\n")) {
          return `"${str.replace(/"/g, '""')}"`;
        }
        return str;
      })
      .join(",")
  );

  // Planning purposes disclaimer
  csvRows.push(`""`);
  csvRows.push(`"Generated by LimitRadar — for planning purposes only. Not accounting or tax advice."`);
  csvRows.push(`"Export date: ${new Date().toISOString()} · Basis: ${basis} · Year: ${year}"`);

  const csv = csvRows.join("\n");

  return new NextResponse(csv, {
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="invoices-${year}-${basis.toLowerCase()}.csv"`,
    },
  });
}
